version: "3"
services:
  nuxt:
    image: nuxt
    ports:
      - "3000:3000"
    command: npm run dev
    # volumes:
    #   - ./src:/app
    # restart: always
    networks:
      mynetwork:
        ipv4_address: 172.32.0.2

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/24